import React from 'react';
import { DRAWING_DATA } from './constants';
import DrawingSection from './components/DrawingSection';

const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-100 font-sans text-slate-800">
      <header className="bg-white shadow-md">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-900">Technical Drawing Extractor</h1>
          <p className="mt-1 text-slate-600">Extracted diagrams from RTX2000 Series Datasheet</p>
        </div>
      </header>
      <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="space-y-12">
          {DRAWING_DATA.map((pageData) => (
            <DrawingSection key={pageData.id} pageData={pageData} />
          ))}
        </div>
      </main>
       <footer className="text-center py-4 text-slate-500 text-sm">
        <p>Generated by World-Class Senior Frontend React Engineer</p>
      </footer>
    </div>
  );
};

export default App;
